"""Generate imports.S: PSP import stubs (.lib.stub records, .rodata.sceNid tables, 8-byte stubs the loader patches).
NID = first 4 bytes (little-endian) of SHA-1(function name) — the public PSP symbol-hash scheme."""
import hashlib, struct, sys

LIBS = {
    'sceDisplay': ['sceDisplaySetMode', 'sceDisplaySetFrameBuf', 'sceDisplayWaitVblankStart'],
    'sceCtrl': ['sceCtrlSetSamplingCycle', 'sceCtrlSetSamplingMode', 'sceCtrlReadBufferPositive'],
    'IoFileMgrForUser': ['sceIoOpen', 'sceIoRead', 'sceIoWrite', 'sceIoClose', 'sceIoMkdir'],
    'sceAudio': ['sceAudioChReserve', 'sceAudioOutputPannedBlocking'],
    'ThreadManForUser': ['sceKernelCreateThread', 'sceKernelStartThread', 'sceKernelDelayThread'],
    'LoadExecForUser': ['sceKernelExitGame'],
}
nid = lambda n: struct.unpack('<I', hashlib.sha1(n.encode()).digest()[:4])[0]
o = ['# generated by gen_imports.py', '\t.set noreorder', '']
o += ['\t.section .rodata.sceResident, "a"'] + [f'name_{l}:\t.asciz "{l}"' for l in LIBS]
o += ['', '\t.section .rodata.sceNid, "a"', '\t.p2align 2']
for l, fs in LIBS.items():
    o += [f'nid_{l}:'] + [f'\t.word 0x{nid(f):08x}\t# {f}' for f in fs]
o += ['', '\t.section .sceStub.text, "ax"', '\t.p2align 2']
for l, fs in LIBS.items():
    o += [f'stub_{l}:']
    for f in fs:
        o += [f'\t.globl {f}', f'\t.type {f}, @function', f'{f}:', '\tjr $ra', '\tnop']
o += ['', '\t.section .lib.stub, "a"', '\t.p2align 2', '\t.globl __lib_stub_top', '__lib_stub_top:']
for l, fs in LIBS.items():
    o += [f'\t.word name_{l}, 0x40010000, 0x{len(fs):04x}0005, nid_{l}, stub_{l}']
o += ['\t.globl __lib_stub_bottom', '__lib_stub_bottom:']
open(sys.argv[1], 'w').write('\n'.join(o) + '\n')
