"""Generate imports.S: PS3 (LV2) import stubs for the HLE system libraries the test program calls.
For each library: a sceLibStub record (.lib.stub), its FNID table and its import slots. The loader (RPCS3, or a real
system) writes the address of each function's descriptor {u32 code, u32 toc} into the slot; a small trampoline per
function loads it, switches TOC, calls, and restores the caller's TOC. FNID = first 4 bytes (LE) of
SHA-1(name + fixed suffix), the public LV2 symbol-hash scheme."""
import hashlib
import struct
import sys

SUFFIX = bytes.fromhex('6759659904250490566427499489741A')
LIBS = {
    'cellGcmSys': ['_cellGcmInitBody', 'cellGcmGetConfiguration', 'cellGcmAddressToOffset', 'cellGcmSetDisplayBuffer', 'cellGcmGetControlRegister',
                   'cellGcmSetFlipMode', 'cellGcmGetFlipStatus', 'cellGcmResetFlipStatus', 'cellGcmSetFlip'],
    'cellSysutil': ['cellVideoOutConfigure', 'cellVideoOutGetState', 'cellSysutilCheckCallback'],
    'sys_io': ['cellPadInit', 'cellPadGetData'],
    'sys_fs': ['cellFsOpen', 'cellFsRead', 'cellFsWrite', 'cellFsClose', 'cellFsMkdir'],
    'cellAudio': ['cellAudioInit', 'cellAudioPortOpen', 'cellAudioPortStart', 'cellAudioGetPortConfig'],
    'sysPrxForUser': ['sys_process_exit'],
}


def fnid(name):
    return struct.unpack('<I', hashlib.sha1(name.encode() + SUFFIX).digest()[:4])[0]


out = ['# generated by gen_imports.py — do not edit', '\t.machine ppc64', '']
out += ['\t.section .rodata.sceResident, "a"']
for lib in LIBS:
    out += [f'name_{lib}:\t.asciz "{lib}"']
out += ['', '\t.section .rodata.sceFNID, "a"', '\t.p2align 2']
for lib, fns in LIBS.items():
    out += [f'fnid_{lib}:'] + [f'\t.long 0x{fnid(f):08x}\t# {f}' for f in fns]
out += ['', '\t.section .data.sceFStub, "aw"', '\t.p2align 2']
for lib, fns in LIBS.items():
    out += [f'slot_{lib}:'] + [f'slot_{f}:\t.long 0' for f in fns]
out += ['', '\t.section .lib.stub, "a"', '\t.p2align 2', '\t.globl __stub_start', '__stub_start:']
for lib, fns in LIBS.items():
    # size, unk0, version, attributes, num_func, num_var, num_tlsvar, info_hash, info_tlshash, unk1[2], name, nids, addrs, vnids, vstubs, unk4, unk5
    out += [f'\t.byte 0x2c, 0', '\t.short 1, 0x0009', f'\t.short {len(fns)}, 0, 0', '\t.byte 0, 0, 0, 0',
            f'\t.long name_{lib}, fnid_{lib}, slot_{lib}, 0, 0, 0, 0']
out += ['\t.globl __stub_end', '__stub_end:', '', '\t.text']
for lib, fns in LIBS.items():
    for f in fns:
        out += [f'\t.globl {f}', f'\t.type {f}, @function', '\t.p2align 2', f'{f}:',
                '\tmflr 0', '\tstd 0, 16(1)', '\tstdu 1, -64(1)', '\tstd 2, 40(1)',
                f'\tlis 12, slot_{f}@ha', f'\tlwz 12, slot_{f}@l(12)',
                '\tlwz 0, 0(12)', '\tlwz 2, 4(12)', '\tmtctr 0', '\tbctrl',
                '\tld 2, 40(1)', '\taddi 1, 1, 64', '\tld 0, 16(1)', '\tmtlr 0', '\tblr', '']
open(sys.argv[1] if len(sys.argv) > 1 else 'imports.S', 'w').write('\n'.join(out) + '\n')
